# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97518ce02f4c553936aea62b750da2c7f927e09026b709729ec35f4ae8fd3460dce554b39ad31f367baa092c3c322fcfc439be840fc5ba30b55af3e87f14ffb3

test:
  secret_key_base: d407ea53a1044132e98e964d78084ef868da1ba432272dea09d5aef58b22b30e8b9b1c69f512c7eec4a1f7e9aec799284a283c795ff12d044411c3849f44514b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
